stages:
- test_p3

testing_py3:
  tags:
  - openshift
  image: python:3.8
  stage: test_p3
  before_script:
  - echo $CI_PROJECT_NAMESPACE
  - echo $CI_REGISTRY
  - echo $CI_PROJECT_PATH
  - virtualenv --clear -p python36 .
  - source ./bin/activate
  script:
  - echo "Installing dependencies"
  - python setup.py install
  - echo "running test on version:"
  - python setup.py --version
  - python -m unittest discover